#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import Iterable
from urllib.parse import quote

from validate_analysis import (
    JsonObject,
    as_object,
    as_object_list,
    as_string_list,
    load_document,
    natural_key,
    validate_document,
)

DOCUMENT_NAMES = ("data-flow.md", "threat-model.md")
GENERATED_NOTICE = (
    "<!-- Generated by render_analysis.py from the canonical analysis ledger. "
    "Do not edit directly. -->"
)
CATEGORY_NAMES = {
    "S": "Spoofing",
    "T": "Tampering",
    "R": "Repudiation",
    "I": "Information Disclosure",
    "D": "Denial of Service",
    "E": "Elevation of Privilege",
}


def text(value: object, default: str = "None") -> str:
    """Return a stable display string for a scalar value."""
    if value is None:
        return default
    if isinstance(value, bool):
        return "yes" if value else "no"
    return str(value)


def integer(value: object, default: int = 0) -> int:
    """Narrow a JSON integer while excluding booleans."""
    return value if isinstance(value, int) and not isinstance(value, bool) else default


def markdown(value: object, default: str = "None") -> str:
    """Escape one value for a Markdown table cell."""
    return (
        text(value, default)
        .replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("\r\n", "<br>")
        .replace("\n", "<br>")
        .replace("\r", "<br>")
    )


def join_values(values: object, default: str = "None") -> str:
    """Join a string array for deterministic display."""
    strings = as_string_list(values)
    return ", ".join(strings) if strings else default


def append_table(
    lines: list[str], headers: tuple[str, ...], rows: Iterable[tuple[object, ...]]
) -> None:
    """Append one Markdown table, or an explicit empty marker.

    Cells are padded to a common column width. That is cosmetic to a reader but load
    bearing for the byte-comparison gate: the widely deployed markdown table formatters
    rewrite tables into exactly this padded shape, so an unpadded table is reformatted
    the first time a repository lint runs. The rendered document then differs from the
    ledger's expected bytes and the package verifier reports the documents as out of
    sync forever after, blaming the model for a formatting change. Emitting the
    canonical padded form up front makes the renderer and those formatters agree, which
    keeps the gate meaningful instead of permanently red.
    """
    materialized = list(rows)
    if not materialized:
        lines.extend(("_None._", ""))
        return
    cells = [list(headers)]
    cells.extend([markdown(value) for value in row] for row in materialized)
    widths = [max(len(row[index]) for row in cells) for index in range(len(headers))]
    lines.append(
        "| " + " | ".join(v.ljust(widths[i]) for i, v in enumerate(cells[0])) + " |"
    )
    lines.append("|" + "|".join("-" * (width + 2) for width in widths) + "|")
    for row in cells[1:]:
        lines.append(
            "| " + " | ".join(v.ljust(widths[i]) for i, v in enumerate(row)) + " |"
        )
    lines.append("")


def ledger_link(ledger_name: str) -> str:
    """Return the package-relative canonical ledger link."""
    return f"[{markdown(ledger_name)}](./{quote(ledger_name)})"


def mermaid_label(value: object) -> str:
    """Escape free text for a quoted Mermaid flowchart label."""
    normalized = " ".join(text(value).split())
    return html.escape(normalized, quote=True)


def sequence_label(value: object) -> str:
    """Normalize free text for Mermaid sequence syntax."""
    normalized = " ".join(text(value).split())
    return normalized.replace(":", " -").replace(";", ",")


def render_flowchart(document: JsonObject) -> list[str]:
    """Render a stable Mermaid flowchart from canonical elements and flows."""
    boundaries = as_object_list(document.get("boundaries")) or []
    elements = as_object_list(document.get("elements")) or []
    flows = as_object_list(document.get("flows")) or []

    grouped: dict[str, list[JsonObject]] = {str(item["id"]): [] for item in boundaries}
    unbounded: list[JsonObject] = []
    for element in elements:
        boundary_ids = as_string_list(element.get("boundaryIds")) or []
        if boundary_ids and boundary_ids[0] in grouped:
            grouped[boundary_ids[0]].append(element)
        else:
            unbounded.append(element)

    lines = ["```mermaid", "flowchart LR"]

    def append_node(element: JsonObject, indent: str = "  ") -> None:
        element_id = str(element["id"])
        label = mermaid_label(
            f"{element_id}: {text(element.get('name'))} [{text(element.get('kind'))}]"
        )
        lines.append(f'{indent}N_{element_id}["{label}"]')

    for element in unbounded:
        append_node(element)
    for boundary in boundaries:
        boundary_id = str(boundary["id"])
        parent = boundary.get("parentId")
        parent_suffix = f"; parent {parent}" if parent else ""
        label = mermaid_label(
            f"{boundary_id}: {text(boundary.get('name'))}{parent_suffix}"
        )
        lines.append(f'  subgraph B_{boundary_id}["{label}"]')
        members = grouped[boundary_id]
        if members:
            for element in members:
                append_node(element, "    ")
        else:
            lines.append("    %% No elements assigned to this boundary")
        lines.append("  end")
    for flow in flows:
        flow_id = str(flow["id"])
        source_id = str(flow["sourceId"])
        target_id = str(flow["targetId"])
        label = mermaid_label(f"{flow_id}: {text(flow.get('name'))}")
        lines.append(f'  N_{source_id} -->|"{label}"| N_{target_id}')
    lines.extend(("```", ""))
    return lines


def render_sequence(document: JsonObject) -> list[str]:
    """Render a stable sequence view of all enumerated flows."""
    elements = as_object_list(document.get("elements")) or []
    flows = as_object_list(document.get("flows")) or []
    lines = ["```mermaid", "sequenceDiagram"]
    for element in elements:
        element_id = str(element["id"])
        label = sequence_label(f"{element_id}: {text(element.get('name'))}")
        lines.append(f"  participant N_{element_id} as {label}")
    for flow in flows:
        flow_id = str(flow["id"])
        source_id = str(flow["sourceId"])
        target_id = str(flow["targetId"])
        label = sequence_label(f"{flow_id}: {text(flow.get('name'))}")
        lines.append(f"  N_{source_id}->>N_{target_id}: {label}")
    lines.extend(("```", ""))
    return lines


def render_data_flow(document: JsonObject, ledger_name: str) -> str:
    """Render data-flow.md from the canonical ledger."""
    scope = as_object(document.get("scope")) or {}
    ownership = as_object(scope.get("ownershipDecision")) or {}
    boundaries = as_object_list(document.get("boundaries")) or []
    elements = as_object_list(document.get("elements")) or []
    flows = as_object_list(document.get("flows")) or []
    assets = as_object_list(document.get("assets")) or []
    threat_actors = as_object_list(document.get("threatActors")) or []
    evidence = as_object_list(document.get("evidence")) or []

    lines = [
        GENERATED_NOTICE,
        "",
        f"# Data Flow: {text(scope.get('name'))}",
        "",
        f"Canonical source: {ledger_link(ledger_name)}",
        "",
        "## Document Information",
        "",
    ]
    append_table(
        lines,
        ("Schema", "Mode", "Lifecycle", "Ownership"),
        [
            (
                document.get("schemaVersion"),
                scope.get("mode"),
                scope.get("lifecycle"),
                ownership.get("action"),
            )
        ],
    )

    lines.extend(("## Trust Boundaries", ""))
    append_table(
        lines,
        ("ID", "Name", "Axis", "Parent", "Evidence"),
        (
            (
                item.get("id"),
                item.get("name"),
                item.get("axis"),
                item.get("parentId"),
                join_values(item.get("evidenceIds")),
            )
            for item in boundaries
        ),
    )

    lines.extend(("## Elements", ""))
    append_table(
        lines,
        ("ID", "Name", "Kind", "Boundaries", "Material", "Evidence"),
        (
            (
                item.get("id"),
                item.get("name"),
                item.get("kind"),
                join_values(item.get("boundaryIds")),
                item.get("material"),
                join_values(item.get("evidenceIds")),
            )
            for item in elements
        ),
    )

    lines.extend(("## Data Flows", ""))
    append_table(
        lines,
        (
            "ID",
            "Name",
            "Source",
            "Target",
            "Assets",
            "Boundary Crossing",
            "Material",
            "Evidence",
        ),
        (
            (
                item.get("id"),
                item.get("name"),
                item.get("sourceId"),
                item.get("targetId"),
                join_values(item.get("assetIds")),
                item.get("crossesTrustBoundary"),
                item.get("material"),
                join_values(item.get("evidenceIds")),
            )
            for item in flows
        ),
    )

    lines.extend(("## Flowchart", ""))
    lines.extend(render_flowchart(document))
    lines.extend(("## Primary Workflow Sequence", ""))
    lines.extend(render_sequence(document))

    lines.extend(("## Assets", ""))
    append_table(
        lines,
        ("ID", "Name", "Classification", "Owner", "Evidence"),
        (
            (
                item.get("id"),
                item.get("name"),
                item.get("classification"),
                item.get("owner"),
                join_values(item.get("evidenceIds")),
            )
            for item in assets
        ),
    )

    lines.extend(("## Threat Actors", ""))
    append_table(
        lines,
        ("ID", "Name", "Capability", "Access", "Target Assets", "Evidence"),
        (
            (
                item.get("id"),
                item.get("name"),
                item.get("capability"),
                join_values(item.get("access")),
                join_values(item.get("targetAssetIds")),
                join_values(item.get("evidenceIds")),
            )
            for item in threat_actors
        ),
    )

    lines.extend(("## Exclusions and Absent Flows", ""))
    exclusions = as_string_list(scope.get("exclusions")) or []
    if exclusions:
        lines.extend(f"- {item}" for item in exclusions)
        lines.append("")
    else:
        lines.extend(("_None recorded._", ""))

    lines.extend(("## Evidence", ""))
    append_table(
        lines,
        ("ID", "Type", "Reference", "Locator", "Claim"),
        (
            (
                item.get("id"),
                item.get("type"),
                item.get("reference"),
                item.get("locator"),
                item.get("claim"),
            )
            for item in evidence
        ),
    )
    return "\n".join(lines).rstrip() + "\n"


def render_threat_model(
    document: JsonObject, ledger_name: str, standalone: bool = False
) -> str:
    """Render threat-model.md from the canonical ledger."""
    scope = as_object(document.get("scope")) or {}
    ownership = as_object(scope.get("ownershipDecision")) or {}
    baseline = as_object(scope.get("baseline")) or {}
    scope_inputs = as_object_list(scope.get("inputs")) or []
    evidence = as_object_list(document.get("evidence")) or []
    boundaries = as_object_list(document.get("boundaries")) or []
    elements = as_object_list(document.get("elements")) or []
    flows = as_object_list(document.get("flows")) or []
    assets = as_object_list(document.get("assets")) or []
    threat_actors = as_object_list(document.get("threatActors")) or []
    coverage = as_object_list(document.get("coverage")) or []
    threats = as_object_list(document.get("threats")) or []
    assumptions = as_object_list(document.get("assumptions")) or []
    summary = as_object(document.get("summary")) or {}
    risk_counts = as_object(summary.get("riskCounts")) or {}

    lines = [
        GENERATED_NOTICE,
        "",
        f"# Threat Model: {text(scope.get('name'))}",
        "",
    ]
    if standalone:
        lines.extend(
            (
                "Generated from a temporary canonical ledger validated before rendering.",
                "",
            )
        )
    else:
        lines.extend(
            (
                f"Canonical source: {ledger_link(ledger_name)}  "
                "\nArchitecture: [data-flow.md](./data-flow.md)",
                "",
            )
        )
    lines.extend(("## Document Information", ""))
    append_table(
        lines,
        ("Schema", "Mode", "Lifecycle", "Ownership", "Model"),
        [
            (
                document.get("schemaVersion"),
                scope.get("mode"),
                scope.get("lifecycle"),
                ownership.get("action"),
                ownership.get("modelReference"),
            )
        ],
    )

    lines.extend(("## Scope", ""))
    append_table(
        lines,
        ("Input", "Kind", "Role", "Reference", "Status", "Evidence", "Rationale"),
        (
            (
                item.get("id"),
                item.get("kind"),
                item.get("role"),
                item.get("reference"),
                item.get("status"),
                join_values(item.get("evidenceIds")),
                item.get("rationale"),
            )
            for item in scope_inputs
        ),
    )
    lines.append(f"Ownership rationale: {text(ownership.get('rationale'))}")
    lines.append("")
    exclusions = as_string_list(scope.get("exclusions")) or []
    lines.append("Exclusions:")
    lines.append("")
    if exclusions:
        lines.extend(f"- {item}" for item in exclusions)
    else:
        lines.append("- None recorded.")
    lines.append("")

    lines.extend(("## Evidence Baseline", ""))
    append_table(
        lines,
        ("Revision", "Date", "Approved By"),
        (
            [
                (
                    baseline.get("revision"),
                    baseline.get("date"),
                    baseline.get("approvedBy"),
                )
            ]
            if baseline
            else []
        ),
    )
    append_table(
        lines,
        ("ID", "Type", "Reference", "Locator", "Claim"),
        (
            (
                item.get("id"),
                item.get("type"),
                item.get("reference"),
                item.get("locator"),
                item.get("claim"),
            )
            for item in evidence
        ),
    )

    lines.extend(("## Architecture Summary", ""))
    append_table(
        lines,
        ("Boundaries", "Elements", "Flows", "Assets", "Threat Actors"),
        [(len(boundaries), len(elements), len(flows), len(assets), len(threat_actors))],
    )

    lines.extend(("## Assets", ""))
    append_table(
        lines,
        ("ID", "Name", "Classification", "Owner", "Evidence"),
        (
            (
                item.get("id"),
                item.get("name"),
                item.get("classification"),
                item.get("owner"),
                join_values(item.get("evidenceIds")),
            )
            for item in assets
        ),
    )

    lines.extend(("## Threat Actors", ""))
    append_table(
        lines,
        ("ID", "Name", "Motivation", "Capability", "Access", "Target Assets"),
        (
            (
                item.get("id"),
                item.get("name"),
                item.get("motivation"),
                item.get("capability"),
                join_values(item.get("access")),
                join_values(item.get("targetAssetIds")),
            )
            for item in threat_actors
        ),
    )

    lines.extend(("## STRIDE Coverage", ""))
    append_table(
        lines,
        ("Target", "Category", "Disposition", "Threats", "Evidence", "Rationale"),
        (
            (
                item.get("targetId"),
                CATEGORY_NAMES.get(str(item.get("category")), item.get("category")),
                item.get("disposition"),
                join_values(item.get("threatIds")),
                join_values(item.get("evidenceIds")),
                item.get("rationale"),
            )
            for item in coverage
        ),
    )

    lines.extend(("## Risk Summary", ""))
    append_table(
        lines,
        ("Critical", "High", "Medium", "Low"),
        [
            (
                risk_counts.get("critical", 0),
                risk_counts.get("high", 0),
                risk_counts.get("medium", 0),
                risk_counts.get("low", 0),
            )
        ],
    )

    triaged = [item for item in threats if as_object_list(item.get("triage"))]
    if triaged:
        latest_rows = [
            (item, (as_object_list(item.get("triage")) or [])[-1]) for item in triaged
        ]
        contested = sum(
            1 for _, entry in latest_rows if entry.get("decision") == "disputed"
        )
        lines.extend(("## Review Dispositions", ""))
        lines.append(
            f"{len(triaged)} of {len(threats)} findings carry a review disposition, "
            f"of which {contested} remain disputed. The latest decision is shown here; "
            "the full trail is recorded under each finding."
        )
        lines.append("")
        append_table(
            lines,
            (
                "Threat",
                "Level",
                "Status",
                "Decision",
                "Reviewer",
                "Date",
                "Work Items",
            ),
            (
                (
                    item.get("id"),
                    item.get("level"),
                    item.get("status"),
                    entry.get("decision"),
                    entry.get("reviewer"),
                    entry.get("date"),
                    join_values(entry.get("workItemIds")),
                )
                for item, entry in latest_rows
            ),
        )

    lines.extend(("## Threat Register", ""))
    append_table(
        lines,
        ("ID", "Title", "Origin", "Status", "Level", "Score", "Targets"),
        (
            (
                item.get("id"),
                item.get("title"),
                item.get("origin"),
                item.get("status"),
                item.get("level"),
                item.get("score"),
                join_values(item.get("targetIds")),
            )
            for item in threats
        ),
    )

    for threat in threats:
        threat_id = str(threat.get("id"))
        lines.extend((f"### {threat_id}: {text(threat.get('title'))}", ""))
        lines.append(text(threat.get("description")))
        lines.append("")
        append_table(
            lines,
            (
                "Category",
                "Origin",
                "Finding Type",
                "Status",
                "Likelihood",
                "Impact",
                "Score",
                "Level",
                "Confidence",
                "Assets",
                "Evidence",
            ),
            [
                (
                    CATEGORY_NAMES.get(
                        str(threat.get("category")), threat.get("category")
                    ),
                    threat.get("origin"),
                    threat.get("findingType"),
                    threat.get("status"),
                    threat.get("likelihood"),
                    threat.get("impact"),
                    threat.get("score"),
                    threat.get("level"),
                    threat.get("confidence"),
                    join_values(threat.get("assetIds")),
                    join_values(threat.get("evidenceIds")),
                )
            ],
        )
        triage_entries = as_object_list(threat.get("triage")) or []
        if triage_entries:
            lines.extend(("#### Review Disposition", ""))
            append_table(
                lines,
                (
                    "Date",
                    "Reviewer",
                    "Decision",
                    "Rationale",
                    "Related",
                    "Work Items",
                    "Evidence",
                    "Reference",
                ),
                (
                    (
                        item.get("date"),
                        item.get("reviewer"),
                        item.get("decision"),
                        item.get("rationale"),
                        join_values(item.get("relatedThreatIds")),
                        join_values(item.get("workItemIds")),
                        join_values(item.get("evidenceIds")),
                        item.get("reference"),
                    )
                    for item in triage_entries
                ),
            )
        lines.extend(("#### Current Controls", ""))
        controls = as_object_list(threat.get("currentControls")) or []
        append_table(
            lines,
            ("Description", "Implementation", "Gap", "Evidence"),
            (
                (
                    item.get("description"),
                    item.get("implementationStatus"),
                    item.get("gap"),
                    join_values(item.get("evidenceIds")),
                )
                for item in controls
            ),
        )
        lines.extend(("#### Mitigation", ""))
        append_table(
            lines,
            ("Action", "Owner", "Location", "Verification"),
            [
                (
                    threat.get("mitigation"),
                    threat.get("mitigationOwner"),
                    threat.get("mitigationLocation"),
                    threat.get("verification"),
                )
            ],
        )

    lines.extend(("## Prioritized Recommendations", ""))
    prioritized = sorted(
        (item for item in threats if item.get("status") in {"open", "unknown"}),
        key=lambda item: (
            -integer(item.get("score")),
            natural_key(str(item.get("id", ""))),
        ),
    )
    append_table(
        lines,
        ("Threat", "Level", "Mitigation", "Owner", "Location", "Verification"),
        (
            (
                item.get("id"),
                item.get("level"),
                item.get("mitigation"),
                item.get("mitigationOwner"),
                item.get("mitigationLocation"),
                item.get("verification"),
            )
            for item in prioritized
        ),
    )

    lines.extend(("## Assumptions and Unknowns", ""))
    append_table(
        lines,
        ("ID", "Kind", "Statement", "Evidence Needed"),
        (
            (
                item.get("id"),
                item.get("kind"),
                item.get("text"),
                item.get("evidenceNeeded"),
            )
            for item in assumptions
        ),
    )

    lines.extend(
        (
            "## Validation",
            "",
            (
                "The temporary canonical ledger passed `validate_analysis.py` before "
                "this standalone report was rendered."
                if standalone
                else "The canonical ledger passed `validate_analysis.py` before "
                "rendering. Run `validate_package.py` to verify rendered-artifact parity."
            ),
            "",
        )
    )
    return "\n".join(lines).rstrip() + "\n"


def render_documents(
    document: JsonObject, ledger_name: str = "analysis.json"
) -> dict[str, str]:
    """Return every deterministic package document keyed by filename."""
    return {
        "data-flow.md": render_data_flow(document, ledger_name),
        "threat-model.md": render_threat_model(document, ledger_name),
    }


def compare_documents(expected: dict[str, str], output_directory: Path) -> list[str]:
    """Return missing or stale generated-document diagnostics."""
    failures: list[str] = []
    for name in DOCUMENT_NAMES:
        path = output_directory / name
        if not path.is_file():
            failures.append(f"missing generated document: {path}")
            continue
        if path.read_text(encoding="utf-8") != expected[name]:
            failures.append(f"stale generated document: {path}")
    return failures


def atomic_write(path: Path, content: str) -> bool:
    """Write changed content atomically and return whether bytes changed."""
    encoded = content.encode("utf-8")
    if path.is_file() and path.read_bytes() == encoded:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(encoded)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, path)
    finally:
        temporary_path.unlink(missing_ok=True)
    return True


def write_documents(expected: dict[str, str], output_directory: Path) -> list[str]:
    """Atomically write generated documents and return changed paths."""
    changed: list[str] = []
    for name in DOCUMENT_NAMES:
        path = output_directory / name
        if atomic_write(path, expected[name]):
            changed.append(str(path))
    return changed


def run_self_test() -> int:
    """Verify byte stability, check mode, and stale-output detection."""
    fixture = Path(__file__).resolve().parents[1] / "assets" / "analysis.example.json"
    document = load_document(fixture)
    errors = validate_document(document)
    if errors:
        raise AssertionError(f"fixture is invalid: {errors}")
    first = render_documents(document)
    second = render_documents(document)
    if first != second:
        raise AssertionError("repeated rendering produced different bytes")
    if not re.search(r"\|\s*manual\s*\|\s*open\s*\|", first["threat-model.md"]):
        raise AssertionError("threat origin and lifecycle status were not rendered")
    separators = [
        line
        for line in first["threat-model.md"].splitlines()
        if set(line) <= {"|", "-"} and "-" in line
    ]
    if not separators:
        raise AssertionError("no table separator rows were rendered")
    for separator in separators:
        row_index = first["threat-model.md"].splitlines().index(separator)
        header = first["threat-model.md"].splitlines()[row_index - 1]
        if len(header) != len(separator):
            raise AssertionError(
                "table cells are not padded to a common width, so a Markdown table "
                f"formatter will rewrite them: {header!r} vs {separator!r}"
            )
    standalone = render_threat_model(document, fixture.name, standalone=True)
    if "analysis.example.json" in standalone or "data-flow.md" in standalone:
        raise AssertionError("standalone report contains a companion-file link")

    with tempfile.TemporaryDirectory() as temporary_directory:
        output_directory = Path(temporary_directory)
        changed = write_documents(first, output_directory)
        if len(changed) != len(DOCUMENT_NAMES):
            raise AssertionError(f"expected both documents to be written: {changed}")
        if compare_documents(first, output_directory):
            raise AssertionError("freshly rendered documents failed check mode")
        if write_documents(second, output_directory):
            raise AssertionError("identical rendering rewrote an unchanged document")
        threat_model = output_directory / "threat-model.md"
        threat_model.write_text(
            threat_model.read_text(encoding="utf-8") + "stale\n", encoding="utf-8"
        )
        failures = compare_documents(first, output_directory)
        if len(failures) != 1 or "stale generated document" not in failures[0]:
            raise AssertionError(f"stale document was not detected: {failures}")

    print("OK: deterministic renderer self-test passed")
    return 0


def main() -> int:
    """Render or check the selected canonical ledger."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ledger", nargs="?", type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--standalone-report", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        return run_self_test()
    if args.ledger is None:
        parser.error("ledger is required unless --self-test is used")

    try:
        document = load_document(args.ledger)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"INVALID: {args.ledger}: {exc}", file=sys.stderr)
        return 1
    errors = validate_document(document)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        print(f"INVALID: {len(errors)} ledger error(s)", file=sys.stderr)
        return 1

    output_directory = args.output_dir or args.ledger.parent
    if args.standalone_report is not None:
        if args.output_dir is not None:
            parser.error("--output-dir cannot be combined with --standalone-report")
        expected_report = render_threat_model(
            document, args.ledger.name, standalone=True
        )
        report_path = args.standalone_report
        if args.check:
            failure = None
            if not report_path.is_file():
                failure = f"missing standalone report: {report_path}"
            elif report_path.read_text(encoding="utf-8") != expected_report:
                failure = f"stale standalone report: {report_path}"
            standalone_result: JsonObject = {
                "valid": failure is None,
                "mode": "check-standalone",
                "ledger": str(args.ledger),
                "report": str(report_path),
                "failures": [failure] if failure else [],
            }
            if args.json:
                print(json.dumps(standalone_result, indent=2))
            elif failure:
                print(f"ERROR: {failure}", file=sys.stderr)
            else:
                print(f"OK: standalone report matches {args.ledger}")
            return 1 if failure else 0

        standalone_changed = atomic_write(report_path, expected_report)
        standalone_result = {
            "valid": True,
            "mode": "write-standalone",
            "ledger": str(args.ledger),
            "report": str(report_path),
            "changed": standalone_changed,
        }
        if args.json:
            print(json.dumps(standalone_result, indent=2))
        else:
            print(
                "OK: rendered standalone report; "
                f"changed {text(standalone_changed).lower()}"
            )
        return 0

    expected = render_documents(document, args.ledger.name)
    if args.check:
        failures = compare_documents(expected, output_directory)
        check_result: JsonObject = {
            "valid": not failures,
            "mode": "check",
            "ledger": str(args.ledger),
            "outputDirectory": str(output_directory),
            "failures": failures,
        }
        if args.json:
            print(json.dumps(check_result, indent=2))
        elif failures:
            for failure in failures:
                print(f"ERROR: {failure}", file=sys.stderr)
        else:
            print(f"OK: generated documents match {args.ledger}")
        return 1 if failures else 0

    package_changed = write_documents(expected, output_directory)
    write_result: JsonObject = {
        "valid": True,
        "mode": "write",
        "ledger": str(args.ledger),
        "outputDirectory": str(output_directory),
        "changed": package_changed,
    }
    if args.json:
        print(json.dumps(write_result, indent=2))
    else:
        print(
            f"OK: rendered {len(DOCUMENT_NAMES)} documents; "
            f"changed {len(package_changed)}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
